name: crypto_baazar
description: A new Flutter project using api for checking crypto price.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4  
  dio: ^4.0.6


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_spinkit: ^5.1.0

 
 # flutter_lints: ^1.0.0


flutter:

 
  uses-material-design: true

  assets:
    - assets/images/

 

  fonts:
   - family: mr
     fonts:
       - asset: fonts/mh.ttf
 
